/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.amf.registration.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AmfRegistrationLog service. Represents a row in the &quot;AMF_REGISTRATION_LOG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.amf.registration.model.impl.AmfRegistrationLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.amf.registration.model.impl.AmfRegistrationLogImpl}.
 * </p>
 *
 * @author liferay
 * @see AmfRegistrationLog
 * @see com.liferay.docs.amf.registration.model.impl.AmfRegistrationLogImpl
 * @see com.liferay.docs.amf.registration.model.impl.AmfRegistrationLogModelImpl
 * @generated
 */
@ProviderType
public interface AmfRegistrationLogModel extends BaseModel<AmfRegistrationLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amf registration log model instance should use the {@link AmfRegistrationLog} interface instead.
	 */

	/**
	 * Returns the primary key of this amf registration log.
	 *
	 * @return the primary key of this amf registration log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amf registration log.
	 *
	 * @param primaryKey the primary key of this amf registration log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the log ID of this amf registration log.
	 *
	 * @return the log ID of this amf registration log
	 */
	public long getLogId();

	/**
	 * Sets the log ID of this amf registration log.
	 *
	 * @param logId the log ID of this amf registration log
	 */
	public void setLogId(long logId);

	/**
	 * Returns the date time of this amf registration log.
	 *
	 * @return the date time of this amf registration log
	 */
	public Date getDateTime();

	/**
	 * Sets the date time of this amf registration log.
	 *
	 * @param dateTime the date time of this amf registration log
	 */
	public void setDateTime(Date dateTime);

	/**
	 * Returns the screen name of this amf registration log.
	 *
	 * @return the screen name of this amf registration log
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this amf registration log.
	 *
	 * @param screenName the screen name of this amf registration log
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the user ID of this amf registration log.
	 *
	 * @return the user ID of this amf registration log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this amf registration log.
	 *
	 * @param userId the user ID of this amf registration log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this amf registration log.
	 *
	 * @return the user uuid of this amf registration log
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this amf registration log.
	 *
	 * @param userUuid the user uuid of this amf registration log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the ip address of this amf registration log.
	 *
	 * @return the ip address of this amf registration log
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this amf registration log.
	 *
	 * @param ipAddress the ip address of this amf registration log
	 */
	public void setIpAddress(String ipAddress);

	/**
	 * Returns the event type of this amf registration log.
	 *
	 * @return the event type of this amf registration log
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this amf registration log.
	 *
	 * @param eventType the event type of this amf registration log
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the additional info of this amf registration log.
	 *
	 * @return the additional info of this amf registration log
	 */
	@AutoEscape
	public String getAdditionalInfo();

	/**
	 * Sets the additional info of this amf registration log.
	 *
	 * @param additionalInfo the additional info of this amf registration log
	 */
	public void setAdditionalInfo(String additionalInfo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AmfRegistrationLog amfRegistrationLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AmfRegistrationLog> toCacheModel();

	@Override
	public AmfRegistrationLog toEscapedModel();

	@Override
	public AmfRegistrationLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}